// src/app/layout.tsx
import React from 'react';
import { Metadata } from 'next';
import Header from '../components/Header';
import Footer from '../components/Footer';

export const metadata: Metadata = {
  title: {
    absolute: "Absloute",
    default: "Defulat",
    template: "Temp",
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main style={{ backgroundColor: '#a0a0a0' }}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
